### ISSUE TITLE
"staticServe" sending wrong file issue

### ISSUE THREAD

**Issue by dnohr** [nanoexpress/middlewares#1]
Hi,

I have been testing this framework today and stubbled over this issue.

I implemented the build-in static file module:
```js
const staticServe = require('nanoexpress-pro/cjs/static');
app.use(staticServe(__dirname + '/public'));
```

I have two files in two different folders:
1. `/public/img/flag/in.svg`
2. `/public/img/testin.svg`

When trying to check in the browser for image number 2 (`example.com/img/testin.svg`), I'm getting the first image instead. You can type any name instead of "test", as long as I have a file ending `in.svg` it will send back the first file.

Thanks a lot.

**Comment by dalisoft** [comment]
No answers, issue was fixed in my env, so i can close the Issue

**Comment by dalisoft** [comment]
@dnohr Please comment here

**Comment by dnohr** [comment]
Hi @dalisoft ,

Sorry for the late reply. I just reinstalled the libraries now to verify it, and with a fresh install, I'm still getting the same or similar issue.

Tested with the following code:
```
const nanoexpress = require('nanoexpress-pro/cjs');
const staticServe = require('nanoexpress-pro/cjs/static');
const app = nanoexpress();
app.use(staticServe(__dirname + '/public'));
app.get('/', (req, res) => { return res.send({ status: 'ok' }); });
app.listen(6006);
```

Try to put two different images in "public/" and a different one in "public/img", but with the same name. Seems like there can only be one static file with the same name.

Thanks.

**Comment by dalisoft** [comment]
I checked this bug already and lot of times. 
Can you please create minimal reproducible repo for test?
Thanks

**Comment by dnohr** [comment]
I'm not sure how to do it fast, but I tested on macOS with just "nanoexpress-pro" installed and two photos in the static folder + in another folder. Thanks!

**Comment by dalisoft** [comment]
Now documentation page related to `static-serve` was removed as documentation lives on this repository for each package

**Comment by dalisoft** [comment]
I sure you are trying to make it work with older package. Please check again
